import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';
import { Root, RootLayout, RootProviders } from '@/src/components/root';
import './globals.css';

export const metadata: Metadata = {
    title: {
        default: 'NFT Marketplace | Home Page',
        template: 'NFT Marketplace | %s',
    },
    description: 'Generated by Dmytro Rogkov',
};

type Props = {
    children: ReactNode;
};

const MainLayout: FC<Props> = ({ children }) => {
    return (
        <Root>
            <RootProviders>
                <RootLayout>{children}</RootLayout>
            </RootProviders>
        </Root>
    );
};

export default MainLayout;
